// Run setup_browser.py, start server.py with that folder's --db and --runtime.
// PLAYWRIGHT_MODULE may point to an already installed Playwright package.
// Usage: node tests/browser.cjs PATH_TO_TEST_RUNTIME
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'), path=require('path'), assert=require('assert');
const tagTranslations=JSON.parse(fs.readFileSync(path.join(__dirname,'..','static','tag-translations.json'),'utf8'));
const runtime=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const folder=path.dirname(process.argv[2]);
assert(folder.includes('test-results'),'Only disposable test services are allowed');
let failurePage, activeBrowser;
const diagnostics=[],network=[];const requests=new Map();
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM||undefined});
 activeBrowser=browser;
 const page=await browser.newPage({viewport:{width:1920,height:1080}});
 failurePage=page;
 page.on('request',r=>requests.set(r,Date.now()));
 page.on('requestfinished',r=>{network.push({path:new URL(r.url()).pathname,ms:Date.now()-(requests.get(r)||Date.now())});requests.delete(r)});
 page.on('requestfailed',r=>{network.push({path:new URL(r.url()).pathname,error:r.failure()?.errorText});requests.delete(r)});
 page.on('console',message=>{if(message.type()==='error')diagnostics.push(message.text())});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const api=async(route,body)=>{const r=await page.request[body===undefined?'get':'post'](runtime.url+route,body===undefined?{}:{data:body,headers:{'X-Mod-Token':runtime.token}});const j=await r.json();assert(j.ok,JSON.stringify(j));return j.data;};
 const initialProfiles=(await api('/api/profiles')).length;
 const profileName='浏览器验收搭配-'+Date.now();
 const t=Date.now();await page.goto(runtime.url);await page.locator('.card').first().waitFor();const openMs=Date.now()-t;
 assert.equal(await page.locator('.card').count(),48);
 assert.equal(await page.locator('[data-game]').count(),(await api('/api/games')).length+1);
 const firstPage=await api('/api/mods?limit=48');
 const cardWithTags=firstPage.items.find(mod=>mod.tags.length);
 assert(cardWithTags,'First page should contain a MOD with Nexus tags');
 const taggedCard=page.locator(`.card[data-id="${cardWithTags.id}"]`);
 assert.equal(await taggedCard.locator('[data-filter-tag]').count(),Math.min(3,cardWithTags.tags.length));
 assert.equal(await taggedCard.locator('[data-add-filter]').count(),Math.min(3,cardWithTags.tags.length));
 assert.equal(await taggedCard.locator('.more-tags').count(),cardWithTags.tags.length>3?1:0);
 const firstCardTag=taggedCard.locator('[data-filter-tag]').first();
 const cardTag=await firstCardTag.getAttribute('data-filter-tag');
 const cardTagText=(await firstCardTag.textContent()).trim();
 assert.equal(cardTagText,tagTranslations[cardTag]||cardTag);
 await firstCardTag.click();
 await page.waitForFunction(({tag,label})=>document.querySelector(`[data-clear="tag"]`)?.textContent.includes(label)&&new URL(location.href).searchParams.get('tag')===tag&&document.querySelector('#pageTitle').textContent.includes('标签：'+label),{tag:cardTag,label:cardTagText});
 assert((await api('/api/mods?tag='+encodeURIComponent(cardTag)+'&limit=48')).items.every(mod=>mod.tags.includes(cardTag)));
 await page.locator('[data-clear="tag"]').click();await page.locator('.card').first().waitFor();
 const addTag=await page.locator('.card [data-add-filter]').first().getAttribute('data-add-filter');
 await page.locator('.card [data-add-filter]').first().click();
 await page.locator('[data-clear="tagsAll"]').waitFor();
 assert((await api('/api/mods?tagsAll='+encodeURIComponent(JSON.stringify([addTag]))+'&limit=48')).items.every(mod=>mod.tags.includes(addTag)));
 await page.locator('[data-clear="tagsAll"]').click();await page.locator('.card').first().waitFor();
 await page.locator('#pageSize').selectOption('24');await page.waitForFunction(()=>document.querySelectorAll('.card').length===24);
 await page.waitForFunction(()=>new URL(location.href).searchParams.get('limit')==='24');
 await page.locator('#pageSize').selectOption('48');await page.waitForFunction(()=>document.querySelectorAll('.card').length===48);
 const savedFilterName='浏览器验收筛选-'+Date.now();
 await page.locator('#sort').selectOption('updated');await page.locator('#saveFilter').click();
 await page.locator('#dialogForm input[name="name"]').fill(savedFilterName);await page.locator('#dialogForm button[type="submit"]').click();
 await page.locator('#savedFilter').selectOption({label:savedFilterName});await page.waitForFunction(()=>document.querySelector('#sort').value==='updated');
 await page.locator('#deleteFilter').click();await page.waitForFunction(name=>![...document.querySelector('#savedFilter').options].some(option=>option.textContent===name),savedFilterName);
 await page.waitForFunction(()=>[...document.querySelectorAll('.card img')].slice(0,6).every(im=>im.complete));
 await page.screenshot({path:path.join(folder,'desktop-1920.png')});
 // Create an explicit empty profile so reruns never toggle a previous run's file.
 await page.locator('[data-view="profiles"]').click();
 await page.locator('#createProfile').click();
 await page.locator('#dialogForm select[name="game"]').selectOption('stellarblade');
 await page.locator('#dialogForm input[name="name"]').fill(profileName);
 await page.locator('#dialogForm button[type="submit"]').click();
 await page.locator('.profile-card').filter({hasText:profileName}).waitFor();
 await page.locator('[data-view="browse"]').click();
 const timings=[];
 for(const game of await api('/api/games')){const t=Date.now();const r=await api('/api/mods?game='+game.id+'&limit=1');assert(r.total>0);timings.push({game:game.id,ms:Date.now()-t,total:r.total});}
 await page.locator('[data-game="reddeadredemption2"]').click();
 await page.locator('.card').first().waitFor();
 assert.equal(await page.locator('.card').count(),48);
 assert(await page.locator('.card .badge').filter({hasText:/中文摘要|正文已导入|部分完成/}).count()>0);
 await page.locator('#search').fill('671');
 await page.locator('.card[data-id="reddeadredemption2:671"]').waitFor();
 await page.locator('.card[data-id="reddeadredemption2:671"] [data-action="open"]').first().click();
 assert(await page.locator('#detailBody .translation-note').first().textContent().then(t=>/本地中文摘要|机器翻译/.test(t)));
 await page.locator('[data-tab="requirements"]').click();
 await page.locator('#detailBody .file-item').first().waitFor();
 await page.locator('[data-tab="files"]').click();
 await page.locator('#detailBody [data-file]').first().waitFor();
 await page.locator('[data-tab="images"]').click();
 await page.locator('#detailBody .gallery-grid button').first().waitFor();
 await page.keyboard.press('Escape');
 await page.locator('#search').fill('');
 await page.locator('[data-game=""]').click();
 await page.keyboard.press('/');assert(await page.locator('#search').evaluate(e=>e===document.activeElement));
 await page.locator('#search').fill('1401');await page.locator('.card[data-id="stellarblade:1401"]').waitFor();
 const realDetailHref=await page.locator('.card[data-id="stellarblade:1401"] .card-title').getAttribute('href');assert(realDetailHref.includes('detail=stellarblade%3A1401'));
 await page.locator('.card[data-id="stellarblade:1401"] [data-action="open"]').first().click();
 await page.waitForFunction(()=>new URL(location.href).searchParams.get('detail')==='stellarblade:1401');
 await page.locator('#editResource').click();await page.locator('textarea[name="function"]').fill('浏览器验收中文摘要');
 await page.locator('#dialogForm button[type="submit"]').click();await page.getByText('资料已保存，可在修改记录中恢复',{exact:true}).waitFor();
 assert.equal((await api('/api/resource?id=stellarblade:1401')).data.function,'浏览器验收中文摘要');
 await page.locator('#editHistory').click();await page.locator('[data-undo-edit]').first().click();
 await page.getByText('资料已恢复；原译文可能需要更新',{exact:true}).waitFor();
 assert.notEqual((await api('/api/resource?id=stellarblade:1401')).data.function,'浏览器验收中文摘要');
 await page.locator('[data-tab="files"]').click();await page.locator('[data-file]').first().waitFor();
 await page.locator('[data-compare]').nth(0).check();await page.locator('[data-compare]').nth(1).check();await page.locator('#compareFiles').click();
 await page.locator('.compare-table').waitFor();await page.locator('#compareClose').click();
 await page.locator('[data-file-action="toggle"]').first().click();
 await page.locator('.file-item.selected').waitFor();
 const profiles=await api('/api/profiles');assert.equal(profiles.length,initialProfiles+1);
 const created=profiles.find(p=>p.name===profileName);assert(created);
 const selected=await api('/api/profile?id='+created.id);assert.equal(selected.items.length,1);
 await page.locator('[data-tab="images"]').click();await page.locator('.gallery-grid button').first().click();await page.locator('#gallery[open]').waitFor();
 await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');
 await page.screenshot({path:path.join(folder,'detail-1920.png')});
 await page.locator('[data-tab="overview"]').click();
 const detailTag=page.locator('[data-filter-tag]').first();
 const clickedTag=await detailTag.getAttribute('data-filter-tag');
 const clickedTagText=(await detailTag.textContent()).trim();
 assert.equal(clickedTagText,tagTranslations[clickedTag]||clickedTag);
 await detailTag.click();
 await page.waitForFunction(tag=>document.querySelector('#detail').hidden&&new URL(location.href).searchParams.get('tag')===tag,clickedTag);
 await page.waitForFunction(label=>document.querySelector('#pageTitle').textContent.includes('标签：'+label),clickedTagText);
 await page.locator('#sort').selectOption('updated');
 const tagged=await api('/api/mods?game=stellarblade&tag='+encodeURIComponent(clickedTag)+'&sort=updated&limit=48');
 assert(tagged.total>0);assert(tagged.items.every(mod=>mod.tags.includes(clickedTag)));
 assert(await page.locator('#detail').isHidden());
 await page.locator('[data-view="profiles"]').click();await page.locator(`[data-profile="${created.id}"]`).click();
 const dl=page.waitForEvent('download');await page.locator('#exportJson').click();const download=await dl;
 const exported=path.join(folder,'selection.json');await download.saveAs(exported);const manifest=JSON.parse(fs.readFileSync(exported,'utf8'));
 assert.equal(manifest.files.length,1);assert.equal(manifest.files[0].fileId,selected.items[0].fileId);
 await page.locator('#profileImportFile').setInputFiles(exported);await page.locator('#applyProfileImport').click();
 await page.getByText('搭配已导入',{exact:true}).waitFor();assert.equal((await api('/api/profiles')).length,initialProfiles+2);
 await page.reload();await page.locator('[data-profile]').first().waitFor();assert.equal(await page.locator('[data-profile]').count(),initialProfiles+2);
 await page.locator('[data-view="settings"]').click();await page.locator('#exportContent').waitFor();
 const resource=await api('/api/resource?id=stellarblade:1401');
 const edits=[{resourceId:resource.resourceId,baseRevision:resource.revision,patch:{function:'批量导入验收'},note:'浏览器隔离测试'}];
 await page.locator('#contentEditsFile').setInputFiles({name:'edits.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(edits))});
 await page.locator('#applyContentEdits').click();await page.getByText('已更新 1 个资源',{exact:true}).waitFor();
 await page.locator('[data-view="browse"]').click();await page.locator('#search').fill('zzzz_no_results');await page.locator('#empty:not([hidden])').waitFor();await page.locator('#emptyClear').click();await page.locator('.card').first().waitFor();
 for(const viewport of [{width:1366,height:768},{width:390,height:844}]){
   await page.setViewportSize(viewport);
   if(viewport.width<800){assert(await page.locator('#filtersPanel').isHidden());await page.locator('#toggleFilters').click();assert(await page.locator('#filtersPanel').isVisible());await page.locator('#toggleFilters').click();}
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow at '+viewport.width);
   await page.screenshot({path:path.join(folder,'browse-'+viewport.width+'.png')});
   await page.locator('.card [data-action="open"]').first().click();await page.locator('#detail:not([hidden])').waitFor();
   assert(await page.locator('#closeDetail').isVisible());await page.keyboard.press('Escape');
 }
 assert.deepEqual(errors,[]);
 assert.deepEqual(diagnostics,[],'Browser console errors');
 fs.writeFileSync(path.join(folder,'browser-report.json'),JSON.stringify({ok:true,openMs,games:timings,errors,checks:[`${timings.length} games`,'24/48 page sizes','compact tag preview and full detail tags','all/any/exclude tag filter state','named saved filters','real detail links and URL history','clickable detail tag filter with sorting','RDR2 Chinese summary, dependencies, files, and local cover','keyboard search','edit and undo','persistent variant comparison','exact file selection','gallery','profile export and import','local reload persistence','batch content import','empty search','1920/1366/390 layouts']},null,2));
 console.log(JSON.stringify({ok:true,openMs,games:timings,errors,folder}));
 await browser.close();
})().catch(async e=>{
 if(failurePage){await failurePage.screenshot({path:path.join(folder,'browser-failure.png')}).catch(()=>{});fs.writeFileSync(path.join(folder,'browser-failure.json'),JSON.stringify({error:String(e),console:diagnostics,network:network.slice(-100),pending:[...requests.keys()].map(r=>new URL(r.url()).pathname),body:await failurePage.locator('body').innerText().catch(()=> '')},null,2));}
 if(activeBrowser)await activeBrowser.close();console.error(e);process.exit(1)
});
